export const WORD_LISTS = {
  easy: [
    "cat",
    "dog",
    "house",
    "tree",
    "car",
    "sun",
    "moon",
    "star",
    "fish",
    "bird",
    "hat",
    "shoe",
    "ball",
    "book",
    "chair",
    "table",
    "door",
    "window",
    "flower",
    "apple",
    "banana",
    "cake",
    "pizza",
    "boat",
    "train",
    "plane",
    "bike",
    "clock",
    "phone",
    "lamp",
    "guitar",
    "drum",
    "heart",
    "cloud",
    "rain",
    "snow",
    "fire",
    "water",
    "mountain",
    "beach",
    "island",
    "bridge",
    "castle",
    "robot",
    "ghost",
    "witch",
    "dragon",
    "crown",
    "sword",
    "shield",
  ],
  medium: [
    "astronaut",
    "telescope",
    "dinosaur",
    "volcano",
    "tornado",
    "earthquake",
    "submarine",
    "helicopter",
    "parachute",
    "trampoline",
    "skateboard",
    "snowboard",
    "surfboard",
    "lighthouse",
    "waterfall",
    "rainbow",
    "butterfly",
    "caterpillar",
    "scorpion",
    "octopus",
    "jellyfish",
    "seahorse",
    "penguin",
    "flamingo",
    "peacock",
    "kangaroo",
    "giraffe",
    "elephant",
    "rhinoceros",
    "campfire",
    "fireworks",
    "carnival",
    "rollercoaster",
    "magician",
    "treasure",
    "pirate",
    "mermaid",
    "unicorn",
    "werewolf",
    "vampire",
    "spaghetti",
    "hamburger",
    "milkshake",
    "pineapple",
    "broccoli",
    "mushroom",
    "sandwich",
    "popcorn",
    "chocolate",
    "lollipop",
  ],
  hard: [
    "photosynthesis",
    "democracy",
    "evolution",
    "constellation",
    "metamorphosis",
    "procrastination",
    "nostalgia",
    "claustrophobia",
    "hallucination",
    "superstition",
    "civilization",
    "architecture",
    "philosophy",
    "mythology",
    "cryptocurrency",
    "biodiversity",
    "electromagnetic",
    "archaeological",
    "choreography",
    "ventriloquist",
    "hieroglyphics",
    "pandemonium",
    "kaleidoscope",
    "seismograph",
    "thermometer",
    "stethoscope",
    "encyclopedia",
    "bibliography",
    "autobiography",
    "onomatopoeia",
  ],
} as const;

export const WORD_CATEGORIES = {
  animals: { label: "Animals", emoji: "🐾" },
  food: { label: "Food & Drink", emoji: "🍕" },
  nature: { label: "Nature", emoji: "🌿" },
  transport: { label: "Transport", emoji: "🚗" },
  objects: { label: "Objects", emoji: "🔧" },
  places: { label: "Places", emoji: "🏰" },
  fantasy: { label: "Fantasy", emoji: "🧙" },
  activities: { label: "Activities", emoji: "🎪" },
  science: { label: "Science", emoji: "🔬" },
  concepts: { label: "Concepts", emoji: "💭" },
} as const;

export type PictionaryCategory = keyof typeof WORD_CATEGORIES;

export const ALL_CATEGORIES = Object.keys(
  WORD_CATEGORIES,
) as PictionaryCategory[];

export const DEFAULT_SETTINGS = {
  roundsPerTeam: 3,
  timerDuration: 60000,
  wordDifficulty: "medium" as "easy" | "medium" | "hard" | "any",
  wordCategories: [] as string[],
};

export type PictionaryDifficulty = keyof typeof WORD_LISTS | "any";
